name: fpl
profile: fpl

flags:
  send_anonymous_usage_stats: false

models:
  fpl:
    staging:
      +materialized: view
      +schema: staging
    marts:
      +materialized: table
      +schema: marts
      