with past_seasons as (

    select
        b.run_date,
        (hp ->> 'element_code')::int as player_code,
        hp ->> 'season_name' as season,
        ((hp ->> 'start_cost')::numeric/10)::numeric(4,1) as start_price,
        ((hp ->> 'end_cost')::numeric/10)::numeric(4,1) as end_price,
        (hp ->> 'total_points')::int as total_points,
        (hp ->> 'minutes')::int as minutes,
        (hp ->> 'starts')::int as starts,
        (hp ->> 'goals_scored')::int as goals_scored,
        (hp ->> 'assists')::int as assists,
        (hp ->> 'clean_sheets')::int as clean_sheets,
        (hp ->> 'goals_conceded')::int as goals_conceded,
        (hp ->> 'own_goals')::int as own_goals,
        (hp ->> 'penalties_saved')::int as penalties_saved,
        (hp ->> 'penalties_missed')::int as penalties_missed,
        (hp ->> 'yellow_cards')::int as yellow_cards,
        (hp ->> 'red_cards')::int as red_cards,
        (hp ->> 'saves')::int as saves,
        (hp ->> 'bonus')::int as bonus,
        (hp ->> 'bps')::int as bps,
        (hp ->> 'clearances_blocks_interceptions')::int as clearances_blocks_interceptions,
        (hp ->> 'recoveries')::int as recoveries,
        (hp ->> 'tackles')::int as tackles,
        (hp ->> 'defensive_contribution')::int as defensive_contribution,
        (hp ->> 'influence')::numeric as influence,
        (hp ->> 'creativity')::numeric as creativity,
        (hp ->> 'threat')::numeric as threat,
        (hp ->> 'ict_index')::numeric as ict_index,
        (hp ->> 'expected_goals')::numeric as expected_goals,
        (hp ->> 'expected_assists')::numeric as expected_assists,
        (hp ->> 'expected_goal_involvements')::numeric as expected_goal_involvements,
        (hp ->> 'expected_goals_conceded')::numeric as expected_goals_conceded
    from {{ ref('base_player_summary_latest') }} as b
    cross join lateral jsonb_array_elements(b.payload -> 'history_past') as hp

)

select distinct on (player_code, season)
    player_code,
    season,
    start_price,
    end_price,
    total_points,
    minutes,
    starts,
    goals_scored,
    assists,
    clean_sheets,
    goals_conceded,
    own_goals,
    penalties_saved,
    penalties_missed,
    yellow_cards,
    red_cards,
    saves,
    bonus,
    bps,
    clearances_blocks_interceptions,
    recoveries,
    tackles,
    defensive_contribution,
    influence,
    creativity,
    threat,
    ict_index,
    expected_goals,
    expected_assists,
    expected_goal_involvements,
    expected_goals_conceded
from past_seasons
order by player_code, season, run_date desc
