select
    b.season,
    (h ->> 'element')::int as player_id,
    (h ->> 'fixture')::int as fixture_id,
    (h ->> 'opponent_team')::int as opponent_team_id,
    (h ->> 'round')::int as gameweek_id,
    (h ->> 'was_home')::boolean as was_home,
    (h ->> 'total_points')::int as total_points,
    (h ->> 'minutes')::int as minutes,
    (h ->> 'starts')::int as starts,
    (h ->> 'goals_scored')::int as goals_scored,
    (h ->> 'assists')::int as assists,
    (h ->> 'clean_sheets')::int as clean_sheets,
    (h ->> 'goals_conceded')::int as goals_conceded,
    (h ->> 'own_goals')::int as own_goals,
    (h ->> 'penalties_saved')::int as penalties_saved,
    (h ->> 'penalties_missed')::int as penalties_missed,
    (h ->> 'yellow_cards')::int as yellow_cards,
    (h ->> 'red_cards')::int as red_cards,
    (h ->> 'saves')::int as saves,
    (h ->> 'bonus')::int as bonus,
    (h ->> 'bps')::int as bps,
    (h ->> 'clearances_blocks_interceptions')::int as clearances_blocks_interceptions,
    (h ->> 'recoveries')::int as recoveries,
    (h ->> 'tackles')::int as tackles,
    (h ->> 'defensive_contribution')::int as defensive_contribution,
    (h ->> 'influence')::numeric as influence,
    (h ->> 'creativity')::numeric as creativity,
    (h ->> 'threat')::numeric as threat,
    (h ->> 'ict_index')::numeric as ict_index,
    (h ->> 'expected_goals')::numeric as expected_goals,
    (h ->> 'expected_assists')::numeric as expected_assists,
    (h ->> 'expected_goal_involvements')::numeric as expected_goal_involvements,
    (h ->> 'expected_goals_conceded')::numeric as expected_goals_conceded,
    ((h ->> 'value')::numeric/10)::numeric(4,1) as price,
    (h ->> 'selected')::int as selected,
    (h ->> 'transfers_in')::int as transfers_in,
    (h ->> 'transfers_out')::int as transfers_out
from {{ ref('base_player_summary_latest') }} as b
cross join lateral jsonb_array_elements(b.payload -> 'history') as h
